### ISSUE TITLE
Consider switching to main area widget

### ISSUE THREAD

**Issue by saulshanabrook** [yuvipanda/jupyter-videochat#3]
We like to keep the side panel widgets for things that are skinny...

Since this might wanna be a bit larger, if you are trying to see someone's notebook, it might be nice to have this also be able to be a main area widget with a launcher icon.

cc @isabela-pf

**Comment by isabela-pf** [comment]
Thanks for mentioning me @saulshanabrook! I also think it would make more sense to have the video interface appear as a main area widget for a few reasons. Most of all, I think having the video in the right side bar as it is now makes it harder to find as that is a less familiar area than a main area widget. Having a normal tab also means it no longer has to rely on harder to read sideways text.

If the video chat was originally put in the sidebar to make sure it was easy to have it next to an open file, I would recommend having Jupyter open with the two tabs side by side (like the below image). I’m pretty sure this can be configured via workspaces.

<img width="1014" alt="Screen Shot 2020-07-01 at 9 50 09 PM" src="https://user-images.githubusercontent.com/50221806/86317689-e8bf2500-bbe4-11ea-88ee-149ca5696bf6.png">

There’s also a chance that this might address #2’s scaling issue since the implementation might have to change some by moving its location.

**Comment by yuvipanda** [comment]
Thanks for chiming in / opening this issue, @saulshanabrook @isabela-pf!

The widget started out as a main area widget, and after testing with a few users I moved it to a sidebar. The use case we developed this for is to have a few students in groups working together. You might screen share, or see someone else's video - but often you'll just 'hide' and use audio only - so you have full screen real estate. I couldn't figure out how to implement 'hide / show' with a main area widget, so it's a sidebar. I kept trying to make the sidebar open to be much wider by default, but after a day trudging through the lumino code I gave up... Almost all the users will also come in via an [nbgitpuller link](https://nbgitpuller.link) so won't ever see the launcher UI.

Do you think we can either:

1. Make it a main area widget that can 'dock' to the sidebar
2. Make the sidebar open wider? I was trying to figure out how to achieve the same thing as the CSS 'min-width' property.

Thank you!

**Comment by saulshanabrook** [comment]
Could we add a way to do both? Where there is a button to pop out the sidebar to a main area widget maybe?

**Comment by bollwyvl** [comment]
I think there are compelling use cases for sidebar, main area, and even second fat browser tab (e.g. you want to share your lab, _and_ be able to see people without the glitch-in-the-matrix effect). I'll maybe have a crack at this...

Also, I had no idea jitsi was all XMPP under the hood. Makes sense! There's a _lot_ we can do with that...
